// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSQOdsCh7ImLhewcIhHUTcj9-1xbShQk',
    appId: '1:533992551897:web:d04a482ad131a0700815c8',
    messagingSenderId: '533992551897',
    projectId: 'lspumart',
    authDomain: 'lspumart.firebaseapp.com',
    storageBucket: 'lspumart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifiplP33rXgwswb7YCL7PtMj9wuK18tE',
    appId: '1:533992551897:android:9b95e0bec39908400815c8',
    messagingSenderId: '533992551897',
    projectId: 'lspumart',
    storageBucket: 'lspumart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbF-Y0fb5KOHbrHXIAikgLDU3BViVbk8',
    appId: '1:533992551897:ios:b00878a2d2fa6d6d0815c8',
    messagingSenderId: '533992551897',
    projectId: 'lspumart',
    storageBucket: 'lspumart.firebasestorage.app',
    iosBundleId: 'com.example.lspu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNbF-Y0fb5KOHbrHXIAikgLDU3BViVbk8',
    appId: '1:533992551897:ios:b00878a2d2fa6d6d0815c8',
    messagingSenderId: '533992551897',
    projectId: 'lspumart',
    storageBucket: 'lspumart.firebasestorage.app',
    iosBundleId: 'com.example.lspu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbSQOdsCh7ImLhewcIhHUTcj9-1xbShQk',
    appId: '1:533992551897:web:436a2e32d60ca0550815c8',
    messagingSenderId: '533992551897',
    projectId: 'lspumart',
    authDomain: 'lspumart.firebaseapp.com',
    storageBucket: 'lspumart.firebasestorage.app',
  );
}
